name: publish with artifact

on:
  push:
    branches: [ main ]

jobs:
  zip-files & publish:
      runs-on: ubuntu-latest
      steps:
        - name: zip
        - uses: actions/checkout@v2
        - uses: papeloto/action-zip@v1
          with:
            files: jlink/
            dest: jlink.zip

