name: publish with artifact

on:
  push:
    branches: [ main ]

jobs:
  zip-files_and_publish:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: zip
        uses: papeloto/action-zip@v1
        with:
          files: jlink/
          dest: jlink.zip
      - name: version
        run: echo "::set-output name=version::$(cat version.md)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: JRE${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: jlink.zip
          asset_name: jlink.zip
          asset_content_type: application/zip

